name: class_alloc
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  get_it: ^7.7.0
  go_router: ^14.2.1
  injectable: ^2.4.4
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - .env
